---
dist: trusty

matrix:
  fast_finish: true

services:
  - docker

install: true

script:
  - docker build -t naftulikay/circleci-lambda-rust .

deploy:
  - provider: script
    script: |
      curl -sSL -i -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/naftulikay/circleci-lambda-rust/trigger/ac972c37-a45e-43da-a157-83f7c394e89e/
    on:
      branch: master

notifications:
  email:
    on_success: never
    on_failure: never
